<?php
declare(strict_types=1);

// Gcal SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

GcalUtility::setRegistrar(function (GcalUtility $u): void {
    $u->clean = [GcalClean::class, 'call'];
    $u->done = [GcalDone::class, 'call'];
    $u->make_error = [GcalMakeError::class, 'call'];
    $u->feature_add = [GcalFeatureAdd::class, 'call'];
    $u->feature_hook = [GcalFeatureHook::class, 'call'];
    $u->feature_init = [GcalFeatureInit::class, 'call'];
    $u->fetcher = [GcalFetcher::class, 'call'];
    $u->make_fetch_def = [GcalMakeFetchDef::class, 'call'];
    $u->make_context = [GcalMakeContext::class, 'call'];
    $u->make_options = [GcalMakeOptions::class, 'call'];
    $u->make_request = [GcalMakeRequest::class, 'call'];
    $u->make_response = [GcalMakeResponse::class, 'call'];
    $u->make_result = [GcalMakeResult::class, 'call'];
    $u->make_point = [GcalMakePoint::class, 'call'];
    $u->make_spec = [GcalMakeSpec::class, 'call'];
    $u->make_url = [GcalMakeUrl::class, 'call'];
    $u->param = [GcalParam::class, 'call'];
    $u->prepare_auth = [GcalPrepareAuth::class, 'call'];
    $u->prepare_body = [GcalPrepareBody::class, 'call'];
    $u->prepare_headers = [GcalPrepareHeaders::class, 'call'];
    $u->prepare_method = [GcalPrepareMethod::class, 'call'];
    $u->prepare_params = [GcalPrepareParams::class, 'call'];
    $u->prepare_path = [GcalPreparePath::class, 'call'];
    $u->prepare_query = [GcalPrepareQuery::class, 'call'];
    $u->graphql_body = [GcalGraphql::class, 'body'];
    $u->graphql_errors = [GcalGraphql::class, 'errors'];
    $u->result_basic = [GcalResultBasic::class, 'call'];
    $u->result_body = [GcalResultBody::class, 'call'];
    $u->result_headers = [GcalResultHeaders::class, 'call'];
    $u->transform_request = [GcalTransformRequest::class, 'call'];
    $u->transform_response = [GcalTransformResponse::class, 'call'];
});
